const songs = [
  {
    id: '1',
    title: 'Self Control',
    artist: 'Frank Ocean',
    album: 'Blonde',
    genre: 'R&B',
    year: 2016,
  },
  {
    id: '2',
    title: 'Shadow Man',
    artist: 'Noname',
    album: 'Telephone',
    genre: 'Hip-Hop/Rap',
    year: 2016,
  },
  {
    id: '3',
    title: 'Above the Clouds',
    artist: 'Gang Starr',
    album: 'Moment of Truth',
    genre: 'Hip-Hop/Rap',
    year: 1998,
  },
  {
    id: '4',
    title: 'Doo Wop (That Thing)',
    artist: 'Lauryn Hill',
    album: 'The Miseducation of Lauryn Hill',
    genre: 'R&B/Soul',
    year: 1998,
  },
  {
    id: '5',
    title: 'Navajo',
    artist: 'Masego',
    album: 'Single',
    genre: 'R&B/Soul',
    year: 2017,
  },
  {
    id: '6',
    title: 'Praise The Lord (da Shine)',
    artist: 'A$AP Rocky',
    album: 'Testing',
    genre: 'Hip-Hop/Rap',
    year: 2018,
  },
  {
    id: '7',
    title: 'Nothing Can Change This Love',
    artist: 'Sam Cooke',
    album: 'The Best of Sam Cooke',
    genre: 'R&B/Soul',
    year: 1960,
  },
  {
    id: '8',
    title: 'Go Gina',
    artist: 'SZA',
    album: 'CTRL',
    genre: 'R&B/Soul',
    year: 2017,
  },
  {
    id: '9',
    title: 'The Waters',
    artist: 'Anderson .Paak',
    album: 'Malibu',
    genre: 'R&B/Soul',
    year: 2016,
  },
];

export default songs;
